[package]
name = "hot_reload"
version = "0.1.0"
edition = "2021"
license = "Unlicense"

[dependencies]
anyhow = "1.0.86"
libloading = "0.8.4"
once_cell = "1.19.0"

[workspace]
members = ["dyn_plugin"]
